### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by Alexdelia** [Goxore/nixconf#2]
https://github.com/Goxore/nixconf/blob/7d0d66587233167e69c2315a8bb27a7f47c72d5b/hosts/laptop/configuration.nix#L38

`lib.mkDefaut` should be `lib.mkDefault`

**Comment by Alexdelia** [comment]
after seeing the typo I've launched [typos](https://github.com/crate-ci/typos) on the `repo` and only found this typo:

https://github.com/Goxore/nixconf/blob/7d0d66587233167e69c2315a8bb27a7f47c72d5b/homeManagerModules/features/ags/notifications.ts#L124

`becuase` -> `because`

there is probably a plugin to add [typos](https://github.com/crate-ci/typos) in your `nvim` config

anyway, thanks for the big contribution you keep giving to the community
you're are doing great

**Comment by vimjoyer** [comment]
`notifications.ts` is unused, and not even my code

**Comment by vimjoyer** [comment]
Might fix typos later
